### ISSUE TITLE
Add top-level Document section to nav

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#10]
The document is such a foundational concept in AsciiDoc that it deserves its own top-level section in the nav. This section is the natural place for the pages about the document type and document header to live. (It's possible that the pages about document attributes could live here, though they are arguably so universal that they still deserve their own top-level section).

Here's the layout I propose:

* Document
  * Document Type
  * Document Header

Document is also a central concept in the API, so having a place to link might make writing about the API easier.

**Comment by graphitefriction** [comment]
This issue has moved to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/17
