### ISSUE TITLE
Document Index Term See and seealso

### ISSUE THREAD

**Issue by loren138** [asciidoctor/asciidoc-docs#120]
I'm excited that see and seealso landed in asciidoctor 2.0:
https://github.com/asciidoctor/asciidoctor/issues/2047
https://github.com/asciidoctor/asciidoctor/pull/3181

But it doesn't look like it made it into the documentation:
https://docs.asciidoctor.org/asciidoc/latest/sections/user-index/#index-terms
https://github.com/asciidoctor/asciidoc-docs/edit/main/docs/modules/sections/pages/user-index.adoc

I'm having a bit of a hard time following the commit that made the change and the thread to figure out the correct syntax.
Would someone be willing to help document that?

**Comment by mojavelinux** [comment]
I'd be glad if someone stepped up to document this feature of the language.

The following tests demonstrate the syntax that's now supported:

https://github.com/asciidoctor/asciidoctor/blob/main/test/substitutions_test.rb#L1495-L1573

In brief, the shorthand delimiter `>>` defines a see term and the shorthand delimiter `&>` defines one or more see also terms.

Here's an example of an index term with a see term (i.e., redirect):

```
(((Flash >> HTML 5)))
```

This is shorthand for:

```
indexterm:[Flash,see=HTML 5]
```

Here's an example of an index term with see also terms:

```
(((HTML 5 &> CSS 3 &> SVG)))
```

This is shorthand for:

```
indexterm:[HTML 5,see-also="CSS 3,SVG"]
```

Both attributes work with the visible index term as well (double round brackets or indexterm2 macro).

There can only be one "see" term. There can be multiple "see also" terms.

**Comment by graphitefriction** [comment]
This issue has moved to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/21.
