### ISSUE TITLE
The preface and appendix are best not to have a section title gap

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoc-docs#125]
Today, I want to use the Book Part feature, so I read [Book Parts | Asciidoctor Docs](https://docs.asciidoctor.org/asciidoc/latest/sections/parts/).

```
= Multi-Part Book with Parts that Have Special Sections
Author Name <author@example.com>
:doctype: book

[preface]
= Book Preface

This is the preface for the whole book.

=== Preface Subsection

Chinchillas rule the world.

= Part 1

This is the introduction to the first part of our mud-encrusted journey.

== Chapter 1

There was mud...

[appendix]
= The Appendix

=== Basics

A multipart book can have appendixes, which should be defined at section level 0.

=== Subsections

Subsections of an appendix in a multipart book should start at level 2.
```

**The `preface` and `appendix` have the `=` Part titles, then have some `===` subsection titles.** 

In my opinion, it is not great. It is inconvenient to manage documents. If do not have the gap, I can write the `preface` in  a document, then include the preface `include::preface.adoc[]`, It is OK. If have the gap, convert the `preface.adoc`, it throw a warn.

If do not have the gap as following:

```
[appendix]
= The Appendix

[appendix]
== Appendix 1

[appendix]
== Appendix 2
```

Then the converted document:

- Appendix A: The Appendix
- Appendix B: Appendix 1
- Appendix C: Appendix 2

**Comment by mojavelinux** [comment]
Please ask questions about AsciiDoc in the Asciidoctor project chat at https://chat.asciidoctor.org. This is not the correct place to have this discussion. There is a reason these offsets are the way they are (and how to deal with includes). I can explain it there.

**Comment by diguage** [comment]
OK.
This is not a question, it is a proposal, so I submit the issue. Let me submit to Chat.

**Comment by mojavelinux** [comment]
It is a question. You are effectively asking why the docs make the recommendation that they do. And there's a reason for it.
