### ISSUE TITLE
Migrate AsciiDoc syntax quick reference

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoc-docs#13]
- Migrate the AsciiDoc syntax quick reference content to syntax-quick-reference.adoc in ROOT module
- Update examples as needed
- Turn included reference tables into xrefs to minimize content duplication
- Add `[%collapsible.result]` to example blocks that show rendered output

**Comment by mojavelinux** [comment]
> Add [%collapsible.result] to example blocks that show rendered output

Already in place :raised_hands: 

The examples also revealed some general styles that were missing, so I'm in the process of getting those added to the UI (and to the Antora default UI).
