### ISSUE TITLE
Fix scope of abstract section style

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#23]
The documentation incorrectly states that the abstract style can only be applied to a section in the article doctype. The abstract style can also be used on a section in the book doctype. In this case, it becomes a chapter, even if defined as a level-0 section (in a multipart book).

**Comment by graphitefriction** [comment]
This issue has been moved to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/15
