### ISSUE TITLE
Set up CHANGELOG file

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoc-docs#28]
Based on a preliminary structure like that for code:

```
= AsciiDoc Documentation Changelog

This document provides a high-level view of the changes introduced into the AsciiDoc Docs

== Released

New::

* Document feature something something (#xyzq)

Improvements::

* Add example about something  (#xyzq)

Fixes::

* Fix incorrect something (#xyzq)

Component / Build / Meta::

* Add alias for something 
* Move attribute to component descriptor
```

Questions:

Since we're not doing versions at the moment, do we want to group changes indicating when they went live, like by date, or do we just want to add inputs to the top of each appropriate list?

Is the purpose of this Changelog to keep a document version of each commit for comparison to the spec's initial contribution or for just general informational purposes?

Do we want this file stored in the root of the repository, or in a module?

**Comment by mojavelinux** [comment]
> Since we're not doing versions at the moment, do we want to group changes indicating when they went live, like by date, or do we just want to add inputs to the top of each appropriate list?

That's a really good question. I would say either do it by quarter (Q4 2020), or just let them accumulate until they get pushed somewhere else, like into the AsciiDoc Language project. If we split it now, it's easy to recombine later (harder to do it the other way around). So I think by quarter makes sense.

> Is the purpose of this Changelog to keep a document version of each commit for comparison to the spec's initial contribution or for just general informational purposes?

I think it's both. It's definitely to help us keep track of what changed, but also helps people who have read the docs to know where to look to update their knowledge. It's also a bit about saving our own tails.

> Do we want this file stored in the root of the repository, or in a module?

Let's put it at the root for now. We can move it into the ROOT module and link it via a symlink if we want to start publishing it. So we don't lose out on that option.

**Comment by mojavelinux** [comment]
Here are the initial changelog entries:

```
Fixed::
* Replace the term "lead style" with the term "lead role"
* Replace frame value "topbot" with "ends" (#9)
* Fix conflict with built-in preamble ID
* Replace document attribute "hardbreaks" with "hardbreaks-option" (#3)
* Fix links to page fragments (aka deep links)
* Fix grouping in nav files
* Update xrefs to reflect module name change in asciidoctor component

Added::
* Import AsciiDoc syntax quick reference (#14)
* Add page about abstract block style to nav and distinguish from abstract section
* Integrate the relative link documentation into the link macro page
* Document where anchor must be placed for item in dlist (#21)

Changed::
* Rework reference table for built-in attributes by fixing incorrect values and descriptions, clarifying difference between effective value and implied value, and consolidating column for Header Only (#24)
* Fold intrinsic attributes reference into document attributes reference (#26)
* Use the term "pair" instead of "set" when referring to formatting mark complements (#6)
* Replace the expression "set of brackets" with the expression "pair of brackets" (#6)
* Replace the expression "set of delimited lines" with the expression "pair of delimited lines" (#6)
* Revise the overview page for text formatting and punctuation (#6)
* Move hard line breaks section to a dedicated page under the Paragraphs section (#3)
* Move unordered lists before ordered lists in nav
* Replace fenced code blocks with AsciiDoc source blocks
* Drop unnecessary quotes in value of subs attribute
* Swap columns in AsciiDoc table cell example
* Use xref macro for interdoc xrefs
* Replace the name "AsciiDoc Python" with "AsciiDoc.py"
* Define navtitle attribute on start page
* Rename version from current to latest

Removed::
* Remove migration in progress notice
* Remove disabled pages
```
