### ISSUE TITLE
Document [%autofit]

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoc-docs#35]
I think [%autofit] is not yet documented. I don't personally use this feature yet, but I saw another user mention it in [this issue](https://github.com/asciidoctor/asciidoctor.org/issues/943)

**Comment by mojavelinux** [comment]
The autofit option is unique to Asciidoctor PDF and is documented here: https://github.com/asciidoctor/asciidoctor-pdf#autofitting-text This is not (yet) a standard option in AsciiDoc itself.
