### ISSUE TITLE
Incorrect include in the images doc

### ISSUE THREAD

**Issue by rkucsora** [asciidoctor/asciidoc-docs#39]
The first code example in the [Images](https://github.com/asciidoctor/asciidoc-docs/blob/7464bb94aed16c59a598704f7fe38d52857c462b/modules/macros/pages/images.adoc) doc shows an `include` statement instead of the content that should be included:

    Content in document.

    include::example$image.adoc[tag=base] (1) (2)

    Content in document

**Comment by mojavelinux** [comment]
The page is working as designed. It first shows the AsciiDoc source, then it shows the result. See https://docs.asciidoctor.org/asciidoc/latest/macros/images/#block-image-macro. If something still does not look right, please reopen and explain what you think is not working.

**Comment by rkucsora** [comment]
I expected to see

    image::sunset.jpg[]

in the AsciiDoc source block in Example 1 and not the include macro. Just as Example 2 later in the doc. The result part looks good.

As I see callouts are added to the include macro causing this problem.

(it looks like I don't have permission to reopen this issue...)

**Comment by Mogztter** [comment]
I think @rkucsora is right, the include directive is not resolved in the documentation site:

![Screenshot_20210113-235449](https://user-images.githubusercontent.com/333276/104520050-c62db000-55fa-11eb-98d0-f6fb2d416a5c.png)

**Comment by mojavelinux** [comment]
Aha! I see now. Thanks for clarifying.

I'll fix it when I get a chance. Feel free to beat me to it.
