### ISSUE TITLE
Section style should be framed as a special section

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#5]
When a section title has a style, that automatically makes it a special section. The documentation should introduce the term "special section" and explain this correlation.

I also question whether we need a separate page for Dedication and Colophon. Except for a handful of exceptions, special sections are just a passthrough designation. For any special section type that AsciiDoc doesn't apply special meaning, they should be grouped on the Special Sections page and just listed. These include: colophon, dedication, acknowledgements. Though we may point out that technical the list is open ended. It's up to the discretion of the converter to handle any additional names.

**Comment by graphitefriction** [comment]
Issue moved to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/14
