### ISSUE TITLE
Create an abridged syntax quick reference

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoc-docs#58]
A slimmed down version of the quick reference with links to detailed sections

**Comment by mojavelinux** [comment]
Although an invaluable resource, the syntax quick reference is not so quick. We should consider making a one page document, perhaps using a different layout, that tries to present the AsciiDoc syntax in the most concise way possible. There are many such attempts floating around, so we can probably build on prior work to slim it down. If we do make this page, we may want to consider reclaiming the the existing page name and moving that one to a detailed syntax reference.

**Comment by mojavelinux** [comment]
We might think about this being "AsciiDoc essentials" or "the most common AsciiDoc you need to know to be productive". It should not be a full reference (like the current syntax quick reference). It should just highlight the most common features a writer will use day to day.

**Comment by graphitefriction** [comment]
This issue has been moved to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/12.
