### ISSUE TITLE
Rename formatting set to formatting pair

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#6]
When we're talking about formatting marks, I think it's more intuitive to refer to them as *formatting pairs" instead of "formatting sets". A pair makes it clear there are two parts (a beginning and an end). A set does not indicate how many items, just that they belong to together.

The same update should be made when talking about constrained or unconstrained formatting marks. In fact, I would prefer the more definitive terminology "constrained formatting pair".

**Comment by Mogztter** [comment]
💯 for pair instead of set!

**Comment by mojavelinux** [comment]
As a general rule, anywhere in the documentation we are talking about complements, we should prefer the term "pair" over "set". For example, a formatting pair, a pair of delimiter lines, a pair of square brackets, etc. (The items in the pair may be the same, like dice, or they may be opposites, like socks). The term "set" should be used when we are talking about an open ended collection of things, such as a set of roles, a set of substitutions, a set of attributes.

In programming, a set has only unique elements. That's generally true when we talk about sets in AsciiDoc. However, in English, a set is defined only as a collection of things that go together (no uniqueness requirement). So if we think of it as "things that go together" I think it will be well understood.

**Comment by graphitefriction** [comment]
Thank you for the clarification @mojavelinux! :+1: for changing from set to pair.
