### ISSUE TITLE
Clarify when to enclose/not enclose an attribute in quotes in ifeval statement

### ISSUE THREAD

**Issue by stoobie** [asciidoctor/asciidoc-docs#65]
On https://docs.asciidoctor.org/asciidoc/latest/directives/ifeval/, there are two examples of testing an attribute's value that could be clearer:

ifeval::["{backend}" == "html5"]
...
endif::[]

ifeval::[{sectnumlevels} == 3]
...
endif::[]

In the first example "{backend}" is in quotes. Why?
In the second example, {sectnumlevels} is _not_ in quotes. Why?

It seems like in both examples you want to test the value of the attribute.

**Comment by mojavelinux** [comment]
Although there's a bit more to it, what it comes down to is whether you're comparing numbers or whether you're comparing strings (letters, words, or phrases). If you are comparing numbers, you don't need (or want) the quotes. When you are comparing strings, you definitely do.

The comparison operation is ultimately passed on to the underlying programming language (Ruby). Those comparison rules are covered on this page: http://www.zenruby.info/2016/05/ruby-operators-equality-comparison.html

**Comment by stoobie** [comment]
@mojavelinux Thanks for the explanation! Is there any reason not to say that in the ifeval page itself?

**Comment by stoobie** [comment]
Whatever the answer to my last question, you can close this issue.

**Comment by mojavelinux** [comment]
It seems reasonable to add that explanation to this page. Would you like to submit a proposed change?

**Comment by stoobie** [comment]
@mojavelinux Another thing that wasn't clear to me: with ifdef/ifndef statements, you can terminate the condition with the same explicit expression that you use to open the condition. For example:
```
ifdef::spider-pig[]
Peter Porker
endif::spider-pig[]
```
Is there a similar way to explicitly terminate an ifeval condition?

**Comment by mojavelinux** [comment]
No, there is not. You can only terminate an ifeval with endif.
