### ISSUE TITLE
Change STEM intepreter to STEM notation

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoc-docs#8]
In the STEM section, the term "STEM interpreter" is being used to refer to the input variant, AsciiMath or LaTeX. For example:

> You can use both interpreters in the same document. The value of the stem attribute merely sets the default interpreter.

However, an interpreter is the software that parses this input and displays the expression for viewing. The term we're looking for here is STEM notation since we're taking about how the input is classified (meaning whether it's assumed to be LaTeX or AsciiMath)

If STEM notation still doesn't seem like a good fit, here are two alternatives:

* STEM markup language
* STEM dialect

**Comment by Mogztter** [comment]
I like both notation and dialect. Notation is probably a "simpler word" than dialect. While STEM markup language is still valid, I feel like it could be misinterpreted since AsciiDoc is also a markup language.

**Comment by mojavelinux** [comment]
I'm leading towards notation as well. The only tricky part is that what the STEM expression produces is referred to as "mathematical notation" or "scientific notation". However, these are also 1-to-1 mappings, so perhaps in context this is not a logical issue.
